title: Flight Simulator Cockpit
description: Temp

theme: just-the-docs
plugins:
   - jekyll-remote-theme #

url: https://sfawcett123.github.io/

defaults:
  - scope:
      path: ""
    values:
      layout: default
      
aux_links:
  Microsoft Flight Simulator: https://www.flightsimulator.com/

