title: Flight Simulator Cockpit
description: Temp
remote_theme: just-the-docs/just-the-docs

url: https://sfawcett123.github.io/

defaults:
  - scope:
      path: ""
    values:
      layout: default
      
aux_links:
  Microsoft Flight Simulator: https://www.flightsimulator.com/

