title: Flight Simulator
description: Temp

theme: minimal-mistakes-jekyll
plugins:
   - jekyll-remote-theme #
   - jekyll-include-cache

url: https://sfawcett123.github.io/

aux_links:
  Microsoft Flight Simulator: https://www.flightsimulator.com/

include:
  - .htaccess
  - _pages

collections:
  articles:
    output: true

author:
  name             : "Steven Fawcett"
  bio              : "Software Engineer"
  location         : "Sunderland - UK"
  email            : "steven.fawcett@me.com"

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/

yaml:
  - filename: https://raw.githubusercontent.com/sfawcett123/Ansible/refs/heads/main/group_vars/raspberry/network.yml
    name: network
