title: Flight Simulator
description: Temp

theme: minimal-mistakes-jekyll
plugins:
   - jekyll-remote-theme #

url: https://sfawcett123.github.io/

aux_links:
  Microsoft Flight Simulator: https://www.flightsimulator.com/

include:
  - .htaccess

collections:
  articles:
    output: true

author:
  name             : "Steven Fawcett"
  bio              : "Software Engineer"
  location         : "Sunderland - UK"
  email            : "steven.fawcett@me.com"
