title: Home DCC Controller
lang: en
description: DCC Controller using an Arduino and Raspberry PI. Based on the DCC++ system.

## local method ##
# theme: jekyll-rtd-theme
# debug:
#   compress: false
#   dist: true
#   shortcodes: true

## remote method ##
remote_theme: alphagov/tech-docs-template

readme_index:
  with_frontmatter: true

exclude:
  - Gemfile
  - Gemfile.lock

